name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y setools lzip wine patchelf e2fsprogs aria2 python3 attr
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build Magusk On WSA
        run: |
          cd ./MagiskOnWSALocal
          scripts/build.sh \
          --arch arm64 \
          --release-type WIF \
          --magisk-ver stable \
          --gapps-brand MindTheGapps \
          --gapps-variant pico \
          --remove-amazon \
          --root-sol magisk
          ls -l
